export default {
  title: "Event Content",
  name: "eventModule",
  type: "object",
  // hidden: true,
  fields: [
    {
      name: "title",
      title: "Title",
      type: "string",
      description: 'Set through your calendar',
      readOnly: true,
    },
    {
      name: "cancelled",
      title: "Cancelled",
      type: "boolean",
      description: 'If true, then this event has been cancelled or deleted through your calendar',
      readOnly: true,
    },
    {
      name: "start",
      title: "Start Date & Time",
      type: "datetime",
      description: 'Set through your calendar',
      readOnly: true,
    },
    {
      name: "end",
      title: "End Date & Time",
      type: "datetime",
      description: 'Set through your calendar',
      readOnly: true,
    },
    {
      name: "location",
      title: "Location",
      type: "string",
      description: 'Set through your calendar',
      readOnly: true,
    },
    {
      name: "description",
      title: "Description",
      type: "text",
      description: 'Set through your calendar',
      readOnly: true,
    },
    {
      name: "descriptionBlocks",
      title: "Description",
      type: "blockContent",
      description: 'Set through your calendar',
      readOnly: true,
    },
    {
      name: "uid",
      title: "UId",
      type: "string",
      description: 'Set through your calendar',
      readOnly: true,
    },
    {
      name: "updated",
      title: "Last Updated",
      type: "datetime",
      description: 'Set through your calendar',
      readOnly: true,
    },
    {
      name: "created",
      title: "Creation Date",
      type: "datetime",
      description: 'Set through your calendar',
      readOnly: true,
    },
    {
      name: "htmlLink",
      title: "Calendar Link",
      type: "url",
      description: 'Set through your calendar',
      readOnly: true,
    },
  ],
};
