yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  "@mdx-js/loader@*":
    peerDependencies:
      react: "^16"
  "@storybook/react@*":
    dependencies:
      "@storybook/core": "next"
  "@theme-ui/mdx@*":
    peerDependencies:
      "@theme-ui/css": "*"
  "@theme-ui/theme-provider@*":
    peerDependencies:
      "@theme-ui/css": "*"
      react: "^16"
  "corejs-upgrade-webpack-plugin@*":
    dependencies:
      core-js: ^2.6.10
      babel-runtime: ^6.26.0
  "theme-ui@^0.3":
    peerDependencies:
      react: "^16"