[build]
  base = "/"
  command = "npm run build:studio && cp packages/studio/netlify.toml packages/studio/dist"
  publish = "/packages/studio/dist"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
