name: Renew calendar notification channels

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  request:
    name: Make request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make request
        uses: ./.github/actions/make-web-request
        with:
          url: ${{ secrets.CALENDAR_NOTIFICATION_CHANNEL_ENDPOINT }}
          method: POST
          headers: '{ "x-jm-app-token": "${{ secrets.CALENDAR_NOTIFICATION_CHANNEL_TOKEN }}", "x-jm-app-method": "renew" }'