name: Make a web request

on:
  schedule:
    - cron: ${{ github.event.inputs.cron }}

jobs:
  request:
    name: Make request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make request
        uses: ./.github/actions/make-web-request
        with:
          url: ${{ github.event.inputs.url }}
          method: ${{ github.event.inputs.method }}
          body: ${{ github.event.inputs.body }}
          headers: ${{ github.event.inputs.headers }}